apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "chronograf.fullname" . }}"
  labels:
    {{- include "chronograf.labels" . | nindent 4 }}
data:
  connection.src: |+
    {
      "id": "10000",
      "name": "influxdb",
      "username": "test",
      "password": "test",
      "url": "{{ include "common-monitoring.influxdburl" . }}",
      "type": "influx",
      "insecureSkipVerify": true,
      "default": true,
      "telegraf": "telegraf",
      "organization": "example_org"
    }