apiVersion: v1
kind: Service
metadata:
  name: {{ template "chronograf.fullname" . }}
  labels:
    {{- include "chronograf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "chronograf.selectorLabels" . | nindent 4}}