apiVersion: v1
kind: Service
metadata:
  name: {{ template "influxdb.fullname" . }}
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: api
    port: {{ .Values.config.http.bind_address | default 8086 }}
    targetPort: api
  - name: rpc
    port: {{ .Values.config.rpc.bind_address | default 8088 }}
    targetPort: rpc
  selector:
    {{- include "influxdb.selectorLabels" . | nindent 4 }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}