# Default values for chronograf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "chronograf"
  tag: 1.8.8
  pullPolicy: IfNotPresent
  pullSecrets: []

## Extra environment variables that will be passed onto deployment pods
env:
  HOST_PAGE_DISABLED: true

## The name of a secret in the same kubernetes namespace which contain values to be added to the environment
## This can be useful for auth tokens, etc
envFromSecret: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8888

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

influxdb:
  url: "http://influxdb:8086"
  database: "telegraf"