apiVersion: v2
name: telegraf
version: 1.7.38
appVersion: 1.18.0
deprecated: false
description: Telegraf is an agent written in Go for collecting, processing, aggregating, and writing metrics.
keywords:
  - telegraf
  - collector
  - timeseries
  - influxdata
  - influxdb
  - agent
home: https://www.influxdata.com/time-series-platform/telegraf/
sources:
  - https://github.com/influxdata/helm-charts/tree/master/charts/telegraf
  - https://github.com/influxdata/helm-charts/
icon: https://avatars0.githubusercontent.com/u/5713248?s=200&v=4
dependencies:
  - name: common-monitoring
    version: 0.0.1
    repository: "file://../common-monitoring"